function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Nov-2017 15:32:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Fantastic Sine Curve','Color',[0 0 0]);
set(plot1(2),'DisplayName','Fantastic Cosine curve','LineStyle','--',...
    'Color',[1 0 0]);
set(plot1(3),'DisplayName','Fantasticer cosine curve','LineStyle',':',...
    'Color',[0 0 1]);

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.579106832545792 0.132063494447678 0.314940786501827 0.114761902377719],...
    'Interpreter','latex');

